### ISSUE TITLE
UML diagram: how to?

### ISSUE THREAD

**Issue by szaghi** [zmiimz/fortran_notes#1]
Dear @zmiimz 

can you give me some suggestions about how to generate UML diagram?

Have you used https://github.com/t2time/ForUML? I have not yet found the time to try it...

Thank you for your help!

Cheers

**Comment by zmiimz** [comment]
Dear Stefano,

It was indeed ForUML. However, I used the old  (compiled by the author) version. You also need ArgoUML in order to see/modify that diagram. There are (were?) few bugs in ForUML (I recall now that 'impure' keyword and preprocessor directives were not recognized). The generated diagram is not always optimal (or even correct), so you need patience and time to bring it to some 'just ok' condition... But anyway, it is a great and handy tool )

**Comment by szaghi** [comment]
Great!

Thank you for your lighting help! :smile: 

Cheers
